### ISSUE TITLE
Docker Ubuntu容器如何配置才能用chacha20加密方法

### ISSUE THREAD

**Issue by teigao** [shadowsocks/shadowsocks-libev#2378]
如题，快被折腾疯了

**Comment by QwertyJack** [comment]
[docker hub](https://hub.docker.com/r/shadowsocks/shadowsocks-libev) 上不是有吗？默认配置就是啊

**Comment by teigao** [comment]
我想问一下ss-local怎么在docker里面使用

**Comment by QwertyJack** [comment]
给你提供几种方法供你选择
假设你的[配置文件](https://shadowsocks.org/en/config/quick-guide.html)是当前目录的 `client.json`

- Native
Ubuntu 官方源里有 shadowsocks-libev，直接安装运行就好了不可以不用 docker
- 直接运行 Docker
```bash
docker run --rm --name ss \
  -v ${PWD}/client.json:/config.json \
  -p <你想监听的本地端口>:1080 \
  shadowsocks/shadowsocks-libev \
  ss-local -u -c /config.json -l 1080
```
- Docker Compose
```yaml
version: "2.2"

services:
  ss:
    image: shadowsocks/shadowsocks-libev
    container_name: ss
    restart: unless-stopped
    ports:
      - "<你想监听的本地端口>:1080"
    volumes:
      - ${PWD}/client.json:/config.json
    command:
      ss-local -u -c /config.json -l 1080
```
