### ISSUE TITLE
[Feature] build Docker OCI Image to support multi platform.

### ISSUE THREAD

**Issue by morlay** [shadowsocks/shadowsocks-libev#2718]
```bash
docker buildx build \
		--push \
		--platform=linux/arm64,linux/amd64 \
		-t=shadowsocks/shadowsocks-libev \
		-f=docker/alpine/Dockerfile \
		.
```

may just use github workflows with secrets `DOCKER_PASSWORD` and `DOCKER_USERNAME`

```yaml
# .github/workflows/build.yml

name: build

on:
  push: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: v0.4.1
      - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - run: | 
         docker buildx build \
           --push \
           --platform=linux/arm64,linux/amd64 \
           -t=shadowsocks/shadowsocks-libev:edge \
           -f=docker/alpine/Dockerfile \
           .
```

see more https://github.com/docker/buildx
demo https://hub.docker.com/r/morlay/shadowsocks-libev/tags
