### ISSUE TITLE
[BOUNTY FOR US$200] ss-manager does not pass "-i" function to generated ss-server

### ISSUE THREAD

**Issue by RebelliousWhiz** [shadowsocks/shadowsocks-libev#2738]
BOUNTY FOR US$200.

Any payment method, or donate to your preferred charity in your name.

### What version of shadowsocks-libev are you using?
3.3.4

### What operating system are you using?
ubuntu 18.04

### What did you do?
ss-manager -c /home/eno1/server/ss-manager/config.json --manager-address 127.0.0.1:12110 -i eno1

### What did you expect to see?
"-i eno1" pass to ss-server

connections are using eno1

### What did you see instead?
"systemctl status ss-manager" and observed no "-i eno1" function passed.

```
   CGroup: /system.slice/eno1ss-manager.service
           ├─2413 /usr/bin/ss-manager -c /home/eno1/server/ss-manager/config.json --manager-address 127.0.0.1:12110 -i eno1
           └─2470 ss-server --manager-address 127.0.0.1:12110 -f /home/eno1/.shadowsocks/.shadowsocks_15625.pid -c /home/eno1/.shadowsocks/.shadowsocks_15625.conf --acl /home/jiayuan/server/ss-manager/server_block_local.acl -t 60 -u -d 8.8.8.8,8.8.4.4,9.9.9.9,1.1.1.1 -s 192.168.110.130
## where is -i eno1?
```

connections are **NOT** using eno1

### What is your config in detail (with all sensitive info masked)?

Init script:

```
[Unit]
Description=eno1ss-manager
After=nta.service
Wants=nta.service

[Service]
Type=simple
User=eno1
Group=jiayuan
ExecStart=/usr/bin/ss-manager -c /home/eno1/server/ss-manager/config.json --manager-address 127.0.0.1:12110 -i eno1

[Install]
WantedBy=multi-user.target
```

**Comment by madeye** [comment]
No plan for this.

**Comment by RebelliousWhiz** [comment]
I will need to use this function for half-commercial purposes... Can I set up a bounty here to ask someone interested in trying to fix it?

**Comment by thesamhurwitz** [comment]
Do you still need it?

**Comment by RebelliousWhiz** [comment]
> Do you still need it?

Yes, my friend. If you could directly contribute to the project will be just fine. The bounty is still valid.

**Comment by thesamhurwitz** [comment]
@RebelliousWhiz , you can contact me via email: contact.samhurwitz@gmail.com

**Comment by RebelliousWhiz** [comment]
I am validating the fix. I am expecting to finish the validation on Oct. 26th.

**Comment by RebelliousWhiz** [comment]
Confirmed fix. To use this feature with shadowsocks-manager, there are lots of settings need to be done.

First of all, you need set proper route table.

Here's my settings in the netplan/01-netcfg.yaml (for 18.04 and newer version).

```
network:
  version: 2
  renderer: networkd
  ethernets:
    eno0:
      match:
        macaddress: fa:16:3e:bf:4d:8b
      addresses:
        - 192.168.100.100/24
      dhcp4: no
      gateway4: 192.168.100.1
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4
      routes:
        - to: 0.0.0.0/0
          via: 192.168.100.1
          table: 100
        - to: 192.168.100.0/24
          via: 192.168.100.1
          table: 100
        - to: 192.168.100.100
          via: 0.0.0.0
          table: 100
      routing-policy:
        - from: 192.168.100.0/24
          table: 100
      set-name: eno0
    eno1:
      match:
        macaddress: fa:16:3e:6e:e1:81
      addresses:
        - 192.168.110.100/24
      dhcp4: no
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4
      routes:
        - to: 0.0.0.0/0
          via: 192.168.110.1
          table: 110
        - to: 192.168.110.0/24
          via: 192.168.110.1
          table: 110
        - to: 192.168.110.100
          via: 0.0.0.0
          table: 110
      routing-policy:
        - from: 192.168.110.0/24
          table: 110
      set-name: eno1
    eno2:
      match:
        macaddress: fa:16:3e:18:6f:8d
      addresses:
        - 192.168.120.100/24
      dhcp4: no
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4
      routes:
        - to: 0.0.0.0/0
          via: 192.168.120.1
          table: 120
        - to: 192.168.120.0/24
          via: 192.168.120.1
          table: 120
        - to: 192.168.120.100
          via: 0.0.0.0
          table: 120
      routing-policy:
        - from: 192.168.120.0/24
          table: 120
      set-name: eno2
    eno3:
      match:
        macaddress: fa:16:3e:17:20:cf
      addresses:
        - 192.168.130.100/24
      dhcp4: no
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4
      routes:
        - to: 0.0.0.0/0
          via: 192.168.130.1
          table: 130
        - to: 192.168.130.0/24
          via: 192.168.130.1
          table: 130
        - to: 192.168.130.100
          via: 0.0.0.0
          table: 130
      routing-policy:
        - from: 192.168.130.0/24
          table: 130
      set-name: eno3
```

Then you will need to grant cap_net_raw compatibility to ss-server and ss-manager executables:

```
setcap cap_net_raw=pe /usr/bin/ss-server
setcap cap_net_raw=pe /usr/bin/ss-manager
```
If you don't do this, you won't be able to forward to different NIC since you don't have the privilege other than using root, but you need other users to run in order to work with ssmgr mechanism.

You may need to do this each time you have updated the shadowsocks-libev.

For each interface, I created a user, to run the systemd, and file save under each home directory.

sample systemd files:

ss-manager:

```
[Unit]
Description=eno0manager
After=nta.service
Wants=nta.service

[Service]
Type=simple
User=eno0
Group=eno0
LimitNOFILE=infinity
ExecStart=/usr/bin/ss-manager -c /home/eno0/server/ss-manager/config.json --manager-address 127.0.0.1:2000 -i eno0

[Install]
WantedBy=multi-user.target
```

ssmgr:

```
[Unit]
Description=eno0ssmgr
Requires=eno0manager.service

[Service]
Type=simple
User=eno0
Group=eno0
ExecStart=/usr/bin/ssmgr -c /home/eno0/server/ssmgr/ssmgr.json

[Install]
WantedBy=multi-user.target
```

And yes, each user uses different systemd files.

Then you will need to make sure the config files of the ss-manager and ssmgr matches the related IP, and also use different manager IP, make sure you use slightly different ports since ssmgr uses ports on 0.0.0.0.

Then with proper tests, you should be able to route the traffic.
