### ISSUE TITLE
有没有运行ss-manager的docker容器？

### ISSUE THREAD

**Issue by jearton** [shadowsocks/shadowsocks-libev#2852]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What did you expect to see?
我想用docker容器方式运行ss-manager，然后通过ss-manager api的方式创建多个ss-server实例

### What did you see instead?
但是目前官方的docker镜像运行的是ss-server

**Comment by Eternity714** [comment]
通过替换entrypoint.sh应该可以解决你的问题

**Comment by navee** [comment]
docker compose
```yml
version: '3'

services:
  shadowsocks:
    image: shadowsocks/shadowsocks-libev
    command: ss-manager -D /data/shadowsocks -c /data/shadowsocks/config.json -u
    volumes:
      - ./conf:/data/shadowsocks
```

docker
```shell
docker run -d -v ./config:/data/shadowsocks shadowsocks/shadowsocks-libev ss-manager -D /data/shadowsocks -c /data/shadowsocks/config.json -u
```
