### ISSUE TITLE
Address not available error

### ISSUE THREAD

**Issue by SonyaCore** [shadowsocks/shadowsocks-libev#2942]
### What version of shadowsocks-libev are you using?
3.3.4

### What operating system are you using?
ubuntu 20.04.4 LTS

### What did you do?
I created a docker-compose file for shadowsocks-libev but when I try to connect with the ss-local it shows show Address not available error in the docker container logs.
<img width="610" alt="image" src="https://user-images.githubusercontent.com/66337103/199761896-7a9c55e6-da8d-4e02-90a8-6e3a5ff5d7d0.png">

### What is your config in detail (with all sensitive info masked)?

```json
{
  "server": "serverip",
  "server_port": 8007,
  "password": "something",
  "timeout": 300,
  "method": "chacha20-ietf-poly1305",
  "mode": "tcp_and_udp"
}
```
and my docker-compose file :

```yaml
version: '3'
services:
  shadowsocks:
    image: shadowsocks/shadowsocks-libev
    ports:
      - "8007:8388"
    environment:
      - TIMEOUT=300
      - METHOD=chacha20-ietf-poly1305
      - PASSWORD=something
    networks:
        overlay:
    restart: always

networks:
    overlay:
        driver: bridge
```
